<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
<?php include 'partials/header.php';?>

<body class=" pi">
    <?php include 'partials/navbar.php';?>
    <section class="main-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-6 col-xs-12">
                    <div class="col-md-6 col-xs-12">
                        <div class="intern-block border-blue">
                            <img src="https://res.cloudinary.com/winnersfield-online/image/upload/v1554346190/linkedin.png" alt="Winner Kelechi">
                            <h6>Winner Kelechi</h6>
                            <p>Front-end Developer</p>
                            <ul class="list">
                                <li><a href="https://twitter.com/Winner01271221" target="_blank" <i class="fab fa-twitter fa-2x"></i></a></li>
                                <li><a href="https://github.com/WinnerKelechi" target="_blank" <i class="fab fa-github fa-2x"></i></a></li>
                                <li><a href="https://medium.com/@kelechiwinner" target="_blank" <i class="fab fa-medium fa-2x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12 align-items-center">
                        <div class="intern-bio border-blue">
                            <h6>About me</h6>
                            <p>I am a front-end developer, a business strategist and a tech enthusiast. I love learning and will never pass up an opportunity to build value. I am a team player and a naturally born leader, i enjoy working with people and sharing ideas. I work with PHP, Laravel, JavaFX and C/C++.</p>
                            <br />
                            <h6>Skills</h6>
                            <p>PHP | Laravel | JavaFX | C/C++</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
</body>
<?php include 'partials/footer.php';?>

</html>
